ALTER TABLE executions ADD COLUMN dirty_frag BOOLEAN DEFAULT FALSE;
ALTER TABLE executions ADD COLUMN fragnesia BOOLEAN DEFAULT FALSE;
ALTER TABLE assets ADD COLUMN dirty_frag BOOLEAN DEFAULT FALSE;
ALTER TABLE assets ADD COLUMN fragnesia BOOLEAN DEFAULT FALSE;
