// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/txlog",
        "contact": {
            "name": "Txlog repository issues",
            "url": "https://github.com/txlog/server/issues"
        },
        "license": {
            "name": "MIT License",
            "url": "https://github.com/txlog/.github/blob/main/profile/LICENSE.md"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/assets/requiring-restart": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "This endpoint retrieves assets that have the latest execution data indicating a restart is required.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "List assets requiring restart",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Invalid JSON input",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Database error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/executions": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "List executions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "executions"
                ],
                "summary": "List executions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Machine ID",
                        "name": "machine_id",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Success",
                        "name": "success",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit (default 100, max 500)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Invalid JSON input",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Database error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a new execution",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "executions"
                ],
                "summary": "Create a new execution",
                "parameters": [
                    {
                        "description": "Execution data",
                        "name": "Execution",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Execution"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Execution created",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "202": {
                        "description": "Execution not created",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON input",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Database error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/items": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get saved items for a transaction",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "items"
                ],
                "summary": "Get saved items for a transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Machine ID",
                        "name": "machine_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Transaction ID. If not provided, the last transaction will be used.",
                        "name": "transaction_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    }
                }
            }
        },
        "/v1/items/ids": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get saved item IDs for a transaction",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "items"
                ],
                "summary": "Get saved item IDs for a transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Machine ID",
                        "name": "machine_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Transaction ID. If not provided, the last transaction will be used.",
                        "name": "transaction_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    }
                }
            }
        },
        "/v1/machines": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "List machine IDs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "List machine IDs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Operating System",
                        "name": "os",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Agent Version",
                        "name": "agent_version",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Invalid JSON input",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Database error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/packages/{name}/{version}/{release}/assets": {
            "get": {
                "description": "Get assets that are using a specific package version",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "packages"
                ],
                "summary": "Get assets that are using a specific package version",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Package name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Package version",
                        "name": "version",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Package release",
                        "name": "release",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Package"
                        }
                    }
                }
            }
        },
        "/v1/reports/anomalies": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Detects unusual transaction patterns like high volume, rapid changes, or downgrades",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Get transaction anomalies",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of days to analyze (default 7)",
                        "name": "days",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Minimum severity filter (low, medium, high)",
                        "name": "severity",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AnomalyReport"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/reports/fixed-vulnerabilities": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns daily aggregated data on vulnerabilities fixed by transactions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Get vulnerability mitigation metrics over time",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of days to look back (default 30)",
                        "name": "days",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.VulnerabilitySeries"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/reports/monthly": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns a list of package updates for a specific month/year, including the number of assets in the period, OS version, package RPM, servers affected, and total updates",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Get monthly package update report",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Month (1-12)",
                        "name": "month",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Year (e.g., 2024)",
                        "name": "year",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.MonthlyReportResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/transactions": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get saved transactions for a host",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Get saved transactions for a host",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Machine ID",
                        "name": "machine_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit (default 100, max 500)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a new transaction",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Create a new transaction",
                "parameters": [
                    {
                        "description": "Transaction data",
                        "name": "Transaction",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Transaction"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transaction created",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON input",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Database error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/transactions/ids": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get saved transactions IDs for a host",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Get saved transactions IDs for a host",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    }
                }
            }
        },
        "/v1/version": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get server version",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "version"
                ],
                "summary": "Get server version",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AnomalyReport": {
            "type": "object",
            "properties": {
                "anomalies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.TransactionAnomaly"
                    }
                },
                "summary": {
                    "$ref": "#/definitions/models.AnomalySummary"
                },
                "time_window": {
                    "type": "string"
                }
            }
        },
        "models.AnomalySeverity": {
            "type": "string",
            "enum": [
                "low",
                "medium",
                "high"
            ],
            "x-enum-varnames": [
                "SeverityLow",
                "SeverityMedium",
                "SeverityHigh"
            ]
        },
        "models.AnomalySummary": {
            "type": "object",
            "properties": {
                "affected_hosts": {
                    "type": "integer"
                },
                "by_severity": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "by_type": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "total_count": {
                    "type": "integer"
                }
            }
        },
        "models.AnomalyType": {
            "type": "string",
            "enum": [
                "high_volume",
                "rapid_change",
                "downgrade"
            ],
            "x-enum-varnames": [
                "AnomalyHighVolume",
                "AnomalyRapidChange",
                "AnomalyDowngrade"
            ]
        },
        "models.Execution": {
            "type": "object",
            "required": [
                "execution_id"
            ],
            "properties": {
                "agent_version": {
                    "type": "string"
                },
                "details": {
                    "type": "string"
                },
                "executed_at": {
                    "type": "string"
                },
                "execution_id": {
                    "type": "string"
                },
                "hostname": {
                    "type": "string"
                },
                "machine_id": {
                    "type": "string"
                },
                "needs_restarting": {
                    "type": "boolean"
                },
                "os": {
                    "type": "string"
                },
                "restarting_reason": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "transactions_processed": {
                    "type": "integer"
                },
                "transactions_sent": {
                    "type": "integer"
                }
            }
        },
        "models.Package": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "arch": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "release": {
                    "type": "string"
                },
                "repo": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "models.Transaction": {
            "type": "object",
            "properties": {
                "actions": {
                    "type": "string"
                },
                "altered": {
                    "type": "string"
                },
                "begin_time": {
                    "type": "string"
                },
                "command_line": {
                    "type": "string"
                },
                "comment": {
                    "type": "string"
                },
                "critical_vulns_fixed": {
                    "type": "integer"
                },
                "critical_vulns_introduced": {
                    "type": "integer"
                },
                "end_time": {
                    "type": "string"
                },
                "high_vulns_fixed": {
                    "type": "integer"
                },
                "high_vulns_introduced": {
                    "type": "integer"
                },
                "hostname": {
                    "type": "string"
                },
                "is_security_patch": {
                    "type": "boolean"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.TransactionItem"
                    }
                },
                "low_vulns_fixed": {
                    "type": "integer"
                },
                "low_vulns_introduced": {
                    "type": "integer"
                },
                "machine_id": {
                    "type": "string"
                },
                "max_severity_fixed": {
                    "type": "string"
                },
                "medium_vulns_fixed": {
                    "type": "integer"
                },
                "medium_vulns_introduced": {
                    "type": "integer"
                },
                "release_version": {
                    "type": "string"
                },
                "return_code": {
                    "type": "string"
                },
                "risk_score_mitigated": {
                    "type": "number"
                },
                "scriptlet_output": {
                    "type": "string"
                },
                "transaction_id": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                },
                "vulnerable_packages_updated": {
                    "type": "integer"
                },
                "vulns_fixed": {
                    "type": "integer"
                },
                "vulns_introduced": {
                    "type": "integer"
                }
            }
        },
        "models.TransactionAnomaly": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "details": {},
                "detected_at": {
                    "type": "string"
                },
                "hostname": {
                    "type": "string"
                },
                "machine_id": {
                    "type": "string"
                },
                "severity": {
                    "$ref": "#/definitions/models.AnomalySeverity"
                },
                "type": {
                    "$ref": "#/definitions/models.AnomalyType"
                }
            }
        },
        "models.TransactionItem": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "arch": {
                    "type": "string"
                },
                "epoch": {
                    "type": "string"
                },
                "from_repo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "release": {
                    "type": "string"
                },
                "repo": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "v1.MonthlyReportPackage": {
            "type": "object",
            "properties": {
                "assets_affected": {
                    "type": "integer"
                },
                "os_version": {
                    "type": "string"
                },
                "package_rpm": {
                    "type": "string"
                }
            }
        },
        "v1.MonthlyReportResponse": {
            "type": "object",
            "properties": {
                "asset_count": {
                    "type": "integer"
                },
                "month": {
                    "type": "integer"
                },
                "packages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.MonthlyReportPackage"
                    }
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "v1.VulnerabilitySeries": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "total_critical_fixed": {
                    "type": "integer"
                },
                "total_fixed": {
                    "type": "integer"
                },
                "total_risk_points_reduced": {
                    "type": "number"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "API key authentication for /v1 endpoints. Generate your API key in the admin panel at /admin",
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Txlog Server",
	Description:      "The centralized system that stores transaction data",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
