// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/txlog",
        "contact": {
            "name": "Txlog repository issues",
            "url": "https://github.com/txlog/server/issues"
        },
        "license": {
            "name": "MIT License",
            "url": "https://github.com/txlog/.github/blob/main/profile/LICENSE.md"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/executions": {
            "get": {
                "description": "List executions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "executions"
                ],
                "summary": "List executions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Machine ID",
                        "name": "machine_id",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Success",
                        "name": "success",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Invalid JSON input",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Database error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new execution",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "executions"
                ],
                "summary": "Create a new execution",
                "parameters": [
                    {
                        "description": "Execution data",
                        "name": "Execution",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Execution"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Execution created",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "202": {
                        "description": "Execution not created",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON input",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Database error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/items": {
            "get": {
                "description": "Get saved items for a transaction",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "items"
                ],
                "summary": "Get saved items for a transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Machine ID",
                        "name": "machine_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Transaction ID. If not provided, the last transaction will be used.",
                        "name": "transaction_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    }
                }
            }
        },
        "/v1/items/ids": {
            "get": {
                "description": "Get saved item IDs for a transaction",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "items"
                ],
                "summary": "Get saved item IDs for a transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Machine ID",
                        "name": "machine_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Transaction ID. If not provided, the last transaction will be used.",
                        "name": "transaction_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    }
                }
            }
        },
        "/v1/machines/ids": {
            "get": {
                "description": "List machine IDs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "machines"
                ],
                "summary": "List machine IDs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hostname",
                        "name": "hostname",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Invalid JSON input",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Database error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/transactions": {
            "get": {
                "description": "Get saved transactions for a host",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Get saved transactions for a host",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Machine ID",
                        "name": "machine_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    }
                }
            },
            "post": {
                "description": "Create a new transaction",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Create a new transaction",
                "parameters": [
                    {
                        "description": "Transaction data",
                        "name": "Transaction",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Transaction"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transaction created",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON input",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Database error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/transactions/ids": {
            "get": {
                "description": "Get saved transactions IDs for a host",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Get saved transactions IDs for a host",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Execution": {
            "type": "object",
            "required": [
                "execution_id"
            ],
            "properties": {
                "agent_version": {
                    "type": "string"
                },
                "details": {
                    "type": "string"
                },
                "executed_at": {
                    "type": "string"
                },
                "execution_id": {
                    "type": "string"
                },
                "hostname": {
                    "type": "string"
                },
                "machine_id": {
                    "type": "string"
                },
                "needs_restarting": {
                    "type": "boolean"
                },
                "os": {
                    "type": "string"
                },
                "restarting_reason": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "transactions_processed": {
                    "type": "integer"
                },
                "transactions_sent": {
                    "type": "integer"
                }
            }
        },
        "models.Transaction": {
            "type": "object",
            "properties": {
                "actions": {
                    "type": "string"
                },
                "altered": {
                    "type": "string"
                },
                "begin_time": {
                    "type": "string"
                },
                "command_line": {
                    "type": "string"
                },
                "comment": {
                    "type": "string"
                },
                "end_time": {
                    "type": "string"
                },
                "hostname": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.TransactionItem"
                    }
                },
                "machine_id": {
                    "type": "string"
                },
                "release_version": {
                    "type": "string"
                },
                "return_code": {
                    "type": "string"
                },
                "scriptlet_output": {
                    "type": "string"
                },
                "transaction_id": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "models.TransactionItem": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "arch": {
                    "type": "string"
                },
                "epoch": {
                    "type": "string"
                },
                "from_repo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "release": {
                    "type": "string"
                },
                "repo": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v1",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{"http", "https"},
	Title:            "Txlog Server",
	Description:      "The centralized system that stores transaction data",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
